in:
  type: file
  path_prefix: example/data.csv
  parser:
    type: csv
    charset: UTF-8
    newline: CRLF
    null_string: 'NULL'
    skip_header_lines: 1
    comment_line_marker: '#'
    columns:
      - {name: time,  type: timestamp, format: "%Y-%m-%d"}
      - {name: id, type: long}
      - {name: name, type: string}
      - {name: score, type: double}

filters:
  - type: left_outer_join_json_table
    base_column: {name: id, type: long}
    counter_column: {name: id, type: long}
    joined_keys_prefix: _joined_by_embulk_
    json_file_path: example/master.json
    json_columns:
      - {name: id, type: long}
      - {name: name, type: string}
      - {name: created_at, type: timestamp, format: "%Y-%m-%d"}
      - {name: point, type: double}
      - {name: time_zone, type: string}

out:
  type: stdout
